export const PAYDAY_BREAKUP_REQUEST = "PAYDAY_BREAKUP_REQUEST";
export const PAYDAY_BREAKUP_SUCCESS = "PAYDAY_BREAKUP_SUCCESS";
export const PAYDAY_BREAKUP_FAILURE = "PAYDAY_BREAKUP_FAILURE";


export const SHORTTERM_BREAKUP_REQUEST = "SHORTTERM_BREAKUP_REQUEST";
export const SHORTTERM_BREAKUP_SUCCESS = "SHORTTERM_BREAKUP_SUCCESS";
export const SHORTTERM_BREAKUP_FAILURE = "SHORTTERM_BREAKUP_FAILURE";



export const GET_BREAKUP_REQUEST = "GET_BREAKUP_REQUEST";
export const GET_BREAKUP_SUCCESS = "GET_BREAKUP_SUCCESS";
export const GET_BREAKUP_FAILURE = "GET_BREAKUP_FAILURE";
