export const CREATE_BU_IN_A_COMPANY_SUCCESS = 'CREATE_BU_IN_A_COMPANY_SUCCESS';
export const CREATE_BU_IN_A_COMPANY_FAILURE = 'CREATE_BU_IN_A_COMPANY_FAILURE';
export const CREATE_BU_IN_A_COMPANY_REQUEST = 'CREATE_BU_IN_A_COMPANY_REQUEST';