export const CREATE_BUISNESS_UNIT_REQUEST = "CREATE_BUISNESS_UNIT_REQUEST";
export const CREATE_BUISNESS_UNIT_SUCCESS = "CREATE_BUISNESS_UNIT_SUCCESS";
export const CREATE_BUISNESS_UNIT_FAILURE = "CREATE_BUISNESS_UNIT_FAILURE";

export const CLEAR_BUISNESS_UNIT = "CLEAR_BUISNESS_UNIT";

export const GET_BUISNESS_UNIT_LIST_REQUEST = "GET_BUISNESS_UNIT_REQUEST";
export const GET_BUISNESS_UNIT_LIST_SUCCESS = "GET_BUISNESS_UNIT_SUCCESS";
export const GET_BUISNESS_UNIT_LIST_FAILURE = "GET_BUISNESS_UNIT_FAILURE";

export const GET_BUISNESS_UNIT_DETAILS_REQUEST =
  "GET_BUISNESS_UNIT_DETAILS_REQUEST";
export const GET_BUISNESS_UNIT_DETAILS_SUCCESS =
  "GET_BUISNESS_UNIT_DETAILS_SUCCESS";
export const GET_BUISNESS_UNIT_DETAILS_FAILURE =
  "GET_BUISNESS_UNIT_DETAILS_FAILURE";

export const UPDATE_BUISNESS_UNIT_REQUEST = "UPDATE_BUISNESS_UNIT_REQUEST";
export const UPDATE_BUISNESS_UNIT_SUCCESS = "UPDATE_BUISNESS_UNIT_SUCCESS";
export const UPDATE_BUISNESS_UNIT_FAILURE = "UPDATE_BUISNESS_UNIT_FAILURE";

export const DELETE_BUISNESS_UNIT_REQUEST = "DELETE_BUISNESS_UNIT_REQUEST";
export const DELETE_BUISNESS_UNIT_SUCCESS = "DELETE_BUISNESS_UNIT_SUCCESS";
export const DELETE_BUISNESS_UNIT_FAILURE = "DELETE_BUISNESS_UNIT_FAILURE";

export const GET_BUISNESS_UNITS_IN_A_COMPANY_REQUEST =
  "GET_BUISNESS_UNITS_IN_A_COMPANY_REQUEST";
export const GET_BUISNESS_UNITS_IN_A_COMPANY_SUCCESS =
  "GET_BUISNESS_UNITS_IN_A_COMPANY_SUCCESS";
export const GET_BUISNESS_UNITS_IN_A_COMPANY_FAILURE =
  "GET_BUISNESS_UNITS_IN_A_COMPANY_FAILURE";

export const SAVE_BU_PRODUCT_REQUEST = "SAVE_BU_PRODUCT_REQUEST";
export const SAVE_BU_PRODUCT_SUCCESS = "SAVE_BU_PRODUCT_SUCCESS";
export const SAVE_BU_PRODUCT_FAILURE = "SAVE_BU_PRODUCT_FAILURE";

export const BU_PRODUCT_TYPE_REQUEST = "BU_PRODUCT_TYPE_REQUEST";
export const BU_PRODUCT_TYPE_SUCCESS = "BU_PRODUCT_TYPE_SUCCESS";
export const BU_PRODUCT_TYPE_FAILURE = "BU_PRODUCT_TYPE_FAILURE";

export const GET_BU_IN_A_LE_REQUEST = "GET_BU_IN_A_LE_REQUEST";
export const GET_BU_IN_A_LE_SUCCESS = "GET_BU_IN_A_LE_SUCCESS";
export const GET_BU_IN_A_LE_FAILURE = "BGET_BU_IN_A_LE_FAILURE";
