export const CREATE_COMPANY_GROUP_REQUEST = "CREATE_COMPANY_GROUP_REQUEST";
export const CREATE_COMPANY_GROUP_SUCCESS = "CREATE_COMPANY_GROUP_SUCCESS";
export const CREATE_COMPANY_GROUP_FAILURE = "CREATE_COMPANY_GROUP_FAILURE";

export const UPDATE_COMPANY_GROUP_REQUEST = "UPDATE_COMPANY_GROUP_REQUEST";
export const UPDATE_COMPANY_GROUP_SUCCESS = "UPDATE_COMPANY_GROUP_SUCCESS";
export const UPDATE_COMPANY_GROUP_FAILURE = "UPDATE_COMPANY_GROUP_FAILURE";

export const GET_COMPANY_GROUP_DETAILS_REQUEST = "GET_COMPANY_GROUP_DETAILS_REQUEST";
export const GET_COMPANY_GROUP_DETAILS_SUCCESS = "GET_COMPANY_GROUP_DETAILS_SUCCESS";
export const GET_COMPANY_GROUP_DETAILS_FAILURE = "GET_COMPANY_GROUP_DETAILS_FAILURE";

export const DELETE_COMPANY_GROUP_REQUEST = "DELETE_COMPANY_GROUP_REQUEST";
export const DELETE_COMPANY_GROUP_SUCCESS = "DELETE_COMPANY_GROUP_SUCCESS";
export const DELETE_COMPANY_GROUP_FAILURE = "DELETE_COMPANY_GROUP_FAILURE";

export const COMPANY_GROUP_LIST_REQUEST = "COMPANY_GROUP_LIST_REQUEST";
export const COMPANY_GROUP_LIST_SUCCESS = "COMPANY_GROUP_LIST_SUCCESS";
export const COMPANY_GROUP_LIST_FAILURE = "COMPANY_GROUP_LIST_FAILURE";