export const CREATE_COUNTRY_REQUEST = "CREATE_COUNTRY_REQUEST";
export const CREATE_COUNTRY_SUCCESS = "CREATE_COUNTRY_SUCCESS";
export const CREATE_COUNTRY_FAILURE = "CREATE_COUNTRY_FAILURE";

export const UPDATE_COUNTRY_REQUEST = "UPDATE_COUNTRY_REQUEST";
export const UPDATE_COUNTRY_SUCCESS = "UPDATE_COUNTRY_SUCCESS";
export const UPDATE_COUNTRY_FAILURE = "UPDATE_COUNTRY_FAILURE";

export const GET_COUNTRY_DETAILS_REQUEST = "GET_COUNTRY_DETAILS_REQUEST";
export const GET_COUNTRY_DETAILS_SUCCESS = "GET_COUNTRY_DETAILS_SUCCESS";
export const GET_COUNTRY_DETAILS_FAILURE = "GET_COUNTRY_DETAILS_FAILURE";

export const DELETE_COUNTRY_REQUEST = "DELETE_COUNTRY_REQUEST";
export const DELETE_COUNTRY_SUCCESS = "DELETE_COUNTRY_SUCCESS";
export const DELETE_COUNTRY_FAILURE = "DELETE_COUNTRY_FAILURE";