export const CREATE_LE_IN_A_GRP_REQUEST = 'CREATE_LE_IN_A_GRP_REQUEST';
export const CREATE_LE_IN_A_GRP_SUCCESS = 'CREATE_LE_IN_A_GRP_SUCCESS';
export const CREATE_LE_IN_A_GRP_FAILURE = 'CREATE_LE_IN_A_GRP_FAILURE';