export const GET_ALL_EMPLOYEES_IN_BU_REQUEST = "GET_ALL_EMPLOYEES_IN_BU_REQUEST";
export const GET_ALL_EMPLOYEES_IN_BU_SUCCESS = "GET_ALL_EMPLOYEES_IN_BU_SUCCESS";
export const GET_ALL_EMPLOYEES_IN_BU_FAILURE = "GET_ALL_EMPLOYEES_IN_BU_FAILURE";


export const GET_PENDING_FOR_APPROVAL_IN_BU_REQUEST = "GET_PENDING_FOR_APPROVAL_IN_BU_REQUEST";
export const GET_PENDING_FOR_APPROVAL_IN_BU_SUCCESS = "GET_PENDING_FOR_APPROVAL_IN_BU_SUCCESS";
export const GET_PENDING_FOR_APPROVAL_IN_BU_FAILURE = "GET_PENDING_FOR_APPROVAL_IN_BU_FAILURE";

export const GET_COMPLETED_LOANS_IN_BU_REQUEST = "GET_COMPLETED_LOANS_IN_BU_REQUEST";
export const GET_COMPLETED_LOANS_IN_BU_SUCCESS = "GET_COMPLETED_LOANS_IN_BU_SUCCESS";
export const GET_COMPLETED_LOANS_IN_BU_FAILURE = "GET_COMPLETED_LOANS_IN_BU_FAILURE";

export const GET_APPROVED_LOANS_IN_BU_REQUEST = "GET_APPROVED_LOANS_IN_BU_REQUEST";
export const GET_APPROVED_LOANS_IN_BU_SUCCESS = "GET_APPROVED_LOANS_IN_BU_SUCCESS";
export const GET_APPROVED_LOANS_IN_BU_FAILURE = "GET_APPROVED_LOANS_IN_BU_FAILURE";


export const GET_UNPAID_LOANS_IN_BU_REQUEST = "GET_UNPAID_LOANS_IN_BU_REQUEST";
export const GET_UNPAID_LOANS_IN_BU_SUCCESS = "GET_UNPAID_LOANS_IN_BU_SUCCESS";
export const GET_UNPAID_LOANS_IN_BU_FAILURE = "GET_UNPAID_LOANS_IN_BU_FAILURE";


export const GET_CURRENT_MONTH_DEDUCTIONS_IN_BU_REQUEST = "GET_CURRENT_MONTH_DEDUCTIONS_IN_BU_REQUEST";
export const GET_CURRENT_MONTH_DEDUCTIONS_IN_BU_SUCCESS = "GET_CURRENT_MONTH_DEDUCTIONS_IN_BU_SUCCESS";
export const GET_CURRENT_MONTH_DEDUCTIONS_IN_BU_FAILURE = "GET_CURRENT_MONTH_DEDUCTIONS_IN_BU_FAILURE";
