export const SAVE_EXCEL_FILE = "SAVE_EXCEL_FILE";

export const GET_SAMPLE_EXCEL_REQUEST = "GET_SAMPLE_EXCEL_REQUEST";
export const GET_SAMPLE_EXCEL_SUCCESS = "GET_SAMPLE_EXCEL_SUCCESS";
export const GET_SAMPLE_EXCEL_FAILURE = "GET_SAMPLE_EXCEL_FAILURE";

export const UPLOAD_EXCEL_REQUEST = "UPLOAD_EXCEL_REQUEST";
export const UPLOAD_EXCEL_SUCCESS = "UPLOAD_EXCEL_SUCCESS";
export const UPLOAD_EXCEL_FAILURE = "UPLOAD_EXCEL_FAILURE";

export const UPLOAD_ZIP_REQUEST = "UPLOAD_ZIP_REQUEST";
export const UPLOAD_ZIP_SUCCESS = "UPLOAD_ZIP_SUCCESS";
export const UPLOAD_ZIP_FAILURE = "UPLOAD_ZIP_FAILURE";

export const SAVE_EXCEL_DATA_REQUEST = "SAVE_EXCEL_DATA_REQUEST";
export const SAVE_EXCEL_DATA_SUCCESS = "SAVE_EXCEL_DATA_SUCCESS";
export const SAVE_EXCEL_DATA_FAILURE = "SAVE_EXCEL_DATA_FAILURE";

export const NEW_EMPLOYEE_UPDATE_EXCEL_REQUEST =
  "NEW_EMPLOYEE_UPDATE_EXCEL__REQUEST";
export const NEW_EMPLOYEE_UPDATE_EXCEL_SUCCESS =
  "NEW_EMPLOYEE_UPDATE_EXCEL_SUCCESS";

export const NEW_EMPLOYEE_UPDATE_EXCEL_FAILURE =
  "NEW_EMPLOYEE_UPDATE_EXCEL_FAILURE";

export const NEW_EMPLOYEE_UPDATE_EXCEL_CLEAR_STATE =
  "NEW_EMPLOYEE_UPDATE_EXCEL_CLEAR_STATE";
