export const UPLOAD_AADHAR_REQUEST = "UPLOAD_AADHAR_REQUEST";
export const UPLOAD_AADHAR_SUCCESS = "UPLOAD_AADHAR_SUCCESS";
export const UPLOAD_AADHAR_FAILURE = "UPLOAD_AADHAR_FAILURE";

export const UPLOAD_PAN_REQUEST = "UPLOAD_PAN_REQUEST";
export const UPLOAD_PAN_SUCCESS = "UPLOAD_PAN_SUCCESS";
export const UPLOAD_PAN_FAILURE = "UPLOAD_PAN_FAILURE";

export const UPLOAD_AADHAR_BACK_REQUEST = "UPLOAD_AADHAR_BACK_REQUEST";
export const UPLOAD_AADHAR__BACK_SUCCESS = "UPLOAD_AADHAR__BACK_SUCCESS";
export const UPLOAD_AADHAR__BACK_FAILURE = "UPLOAD_AADHAR__BACK_FAILURE";

export const DOWNLOAD_AADHAR_BACK_REQUEST = "DOWNLOAD_AADHAR_BACK_REQUEST";
export const DOWNLOAD_AADHAR__BACK_SUCCESS = "DOWNLOAD_AADHAR__BACK_SUCCESS";
export const DOWNLOAD_AADHAR__BACK_FAILURE = "DOWNLOAD_AADHAR__BACK_FAILURE";
