export const GET_FINANCIAL_YEAR_REQUEST = "GET_FINANCIAL_YEAR_REQUEST";
export const GET_FINANCIAL_YEAR_SUCCESS = "GET_FINANCIAL_YEAR_SUCCESS";
export const GET_FINANCIAL_YEAR_FAILURE = "GET_FINANCIAL_YEAR_FAILURE";