
  


export const SAVE_BASIC_INFO = "SAVE_BASIC_INFO";
export const SAVE_SALARY_INFO = "SAVE_SALARY_INFO";


export const SAVE_BIWEEKLY_SALARY_INFO_FORM="SAVE_BIWEEKLY_SALARY_INFO_FORM"


export const SAVE_FILTERED_PARAMS="SAVE_FILTERED_PARAMS"
