export const CREATE_GROUP_ENTITY_REQUEST = "CREATE_GROUP_ENTITY_REQUEST";
export const CREATE_GROUP_ENTITY_SUCCESS = "CREATE_GROUP_ENTITY_SUCCESS";
export const CREATE_GROUP_ENTITY_FAILURE = "CREATE_GROUP_ENTITY_FAILURE";


export const LOAD_GROUP_ENTITY_REQUEST = "LOAD_GROUP_ENTITY_REQUEST";
export const LOAD_GROUP_ENTITY_SUCCESS = "LOAD_GROUP_ENTITY_SUCCESS";
export const LOAD_GROUP_ENTITY_FAILURE = "LOAD_GROUP_ENTITY_FAILURE";

export const GET_GROUP_ENTITY_DETAILS_REQUEST = "GET_GROUP_ENTITY_DETAILS_REQUEST";
export const GET_GROUP_ENTITY_DETAILS_SUCCESS = "GET_GROUP_ENTITY_DETAILS_SUCCESS";
export const GET_GROUP_ENTITY_DETAILS_FAILURE = "GET_GROUP_ENTITY_DETAILS_FAILURE";

export const GROUP_ENTITY_LIST_REQUEST="GROUP_ENTITY_LIST_REQUEST";
export const GROUP_ENTITY_LIST_SUCCESS="GROUP_ENTITY_LIST_SUCCESS";
export const GROUP_ENTITY_LIST_FAILURE="GROUP_ENTITY_LIST_FAILURE";

export const UPDATE_GROUP_ENTITY_REQUEST = "UPDATE_GROUP_ENTITY_REQUEST";
export const UPDATE_GROUP_ENTITY_SUCCESS = "UPDATE_GROUP_ENTITY_SUCCESS";
export const UPDATE_GROUP_ENTITY_FAILURE = "UPDATE_GROUP_ENTITY_FAILURE";

export const DELETE_GROUP_ENTITY_REQUEST = "DELETE_GROUP_ENTITY_REQUEST";
export const DELETE_GROUP_ENTITY_SUCCESS = "DELETE_GROUP_ENTITY_SUCCESS";
export const DELETE_GROUP_ENTITY_FAILURE = "DELETE_GROUP_ENTITY_FAILURE";

export const GET_GROUP_CODES_REQUEST="GET_GROUP_CODES_REQUEST";
export const GET_GROUP_CODES_SUCCESS="GET_GROUP_CODES_SUCCESS";
export const GET_GROUP_CODES_FAILURE="GET_GROUP_CODES_FAILURE";


export const GET_ACTIVE_GROUPS_LIST_REQUEST="GET_ACTIVE_GROUPS_LIST_REQUEST";
export const GET_ACTIVE_GROUPS_LIST_SUCCESS="GET_ACTIVE_GROUPS_LIST_SUCCESS";
export const GET_ACTIVE_GROUPS_LIST_FAILURE="GET_ACTIVE_GROUPS_LIST_FAILURE";

export const CLEAR_GROUP_ENTITY="CLEAR_GROUP_ENTITY"

