export const CREATE_LEGAL_ENTITY_REQUEST = "CREATE_LEGAL_ENTITY_REQUEST";
export const CREATE_LEGAL_ENTITY_SUCCESS = "CREATE_LEGAL_ENTITY_SUCCESS";
export const CREATE_LEGAL_ENTITY_FAILURE = "CREATE_LEGAL_ENTITY_FAILURE";
export const CLEAR_LEGAL_ENTITY="CLEAR_LEGAL_ENTITY"

export const LOAD_LEGAL_ENTITY_REQUEST = "LOAD_LEGAL_ENTITY_REQUEST";
export const LOAD_LEGAL_ENTITY_SUCCESS = "LOAD_LEGAL_ENTITY_SUCCESS";
export const LOAD_LEGAL_ENTITY_FAILURE = "LOAD_LEGAL_ENTITY_FAILURE";

export const GET_LEGAL_ENTITY_DETAILS_REQUEST = "GET_LEGAL_ENTITY_DETAILS_REQUEST";
export const GET_LEGAL_ENTITY_DETAILS_SUCCESS = "GET_LEGAL_ENTITY_DETAILS_SUCCESS";
export const GET_LEGAL_ENTITY_DETAILS_FAILURE = "GET_LEGAL_ENTITY_DETAILS_FAILURE";



export const UPDATE_LEGAL_ENTITY_REQUEST = "UPDATE_LEGAL_ENTITY_REQUEST";
export const UPDATE_LEGAL_ENTITY_SUCCESS = "UPDATE_LEGAL_ENTITY_SUCCESS";
export const UPDATE_LEGAL_ENTITY_FAILURE = "UPDATE_LEGAL_ENTITY_FAILURE";

export const DELETE_LEGAL_ENTITY_REQUEST = "DELETE_LEGAL_ENTITY_REQUEST";
export const DELETE_LEGAL_ENTITY_SUCCESS = "DELETE_LEGAL_ENTITY_SUCCESS";
export const DELETE_LEGAL_ENTITY_FAILURE = "DELETE_LEGAL_ENTITY_FAILURE";

export const GET_LEGAL_ENTITES_IN_A_GROUP_REQUEST="GET_LEGAL_ENTITES_IN_A_GROUP_REQUEST";
export const GET_LEGAL_ENTITES_IN_A_GROUP_SUCCESS="GET_LEGAL_ENTITES_IN_A_GROUP_SUCCESS";
export const GET_LEGAL_ENTITES_IN_A_GROUP_FAILURE="GET_LEGAL_ENTITES_IN_A_GROUP_FAILURE";