export const LIST_REQUEST="LIST_REQUEST";
export const LIST_SUCCESS="LIST_SUCCESS";
export const LIST_FAILURE="LIST_FAILURE";


export const LIST_DETAILS_REQUEST="LIST_DETAILS";
export const LIST_DETAILS_SUCCESS="LIST_DETAILS_SUCCESS";
export const LIST_DETAILS_FAILURE="LIST_DETAILS_FAILURE";
