export const LOAN_TYPE_REQUEST = "LOAN_TYPE_REQUEST";
export const LOAN_TYPE_SUCCESS = "LOAN_TYPE_SUCCESS";
export const LOAN_TYPE_FAILURE = "LOAN_TYPE_FAILURE";

export const CREATE_LOAN_MASTER_REQUEST = "CREATE_LOAN_MASTER_REQUEST";
export const CREATE_LOAN_MASTER_SUCCESS = "CREATE_LOAN_MASTER_SUCCESS";
export const CREATE_LOAN_MASTER_FAILURE = "CREATE_LOAN_MASTER_FAILURE";

export const CLEAR_LOAN_MASTER = "CLEAR_LOAN_MASTER";

export const PRODUCT_SAVE_OR_UPDATE_REQUEST = "PRODUCT_SAVE_OR_UPDATE_REQUEST";
export const PRODUCT_SAVE_OR_UPDATE_SUCCESS = "PRODUCT_SAVE_OR_UPDATE_SUCCESS";
export const PRODUCT_SAVE_OR_UPDATE_FAILURE = "PRODUCT_SAVE_OR_UPDATE_FAILURE";

export const PRODUCT_FETCH_REQUEST = "PRODUCT_FETCH_REQUEST";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAILURE = "PRODUCT_FETCH_FAILURE";

export const PRODUCT_FILTER_REQUET = "PRODUCT_FILTER_REQUET";
export const PRODUCT_FILTER_SUCCESS = "PRODUCT_FILTER_SUCCESS";
export const PRODUCT_FILTER_FAILURE = "PRODUCT_FILTER_FAILURE";

export const PRODUCT_FILTER_REQUET2 = "PRODUCT_FILTER_REQUET2";
export const PRODUCT_FILTER_SUCCESS2 = "PRODUCT_FILTER_SUCCESS2";
export const PRODUCT_FILTER_FAILURE2 = "PRODUCT_FILTER_FAILURE2";

export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAILURE = "GET_ALL_PRODUCTS_FAILURE";

export const MANUAL_AUTHORITY_REQUEST = "MANUAL_AUTHORITY_REQUEST";
export const MANUAL_AUTHORITY_SUCCESS = "MANUAL_AUTHORITY_SUCCESS";
export const MANUAL_AUTHORITY_FAILURE = "MANUAL_AUTHORITY_FAILURE";

export const MANUAL_AUTHORITY_PREREQUISITES = "MANUAL_AUTHORITY_PREREQUISITES";


export const BU_LEVEL_LOAN_PRODUCT_UPDATE_REQUEST="BU_LEVEL_LOAN_PRODUCT_UPDATE_REQUEST"
export const BU_LEVEL_LOAN_PRODUCT_UPDATE_SUCCESS="BU_LEVEL_LOAN_PRODUCT_UPDATE_SUCCESS"
export const BU_LEVEL_LOAN_PRODUCT_UPDATE_FAILURE="BU_LEVEL_LOAN_PRODUCT_UPDATE_FAILURE"


export const LOAN_REQUEST_DETAILS_REQUEST="LOAN_REQUEST_DETAILS_REQUEST"
export const LOAN_REQUEST_DETAILS_SUCCESS="LOAN_REQUEST_DETAILS_SUCCESS"
export const LOAN_REQUEST_DETAILS_FAILURE="LOAN_REQUEST_DETAILS_FAILURE"




export const HR_APPROVAL_REQUEST="HR_APPROVAL_REQUEST"
export const HR_APPROVAL_SUCCESS="HR_APPROVAL_SUCCESS"
export const HR_APPROVAL_FAILURE="HR_APPROVAL_FAILURE"


export const LOAN_DISBURSAL_REQUEST="LOAN_DISBURSAL_REQUEST"
export const LOAN_DISBURSAL_SUCCESS="LOAN_DISBURSAL_SUCCESS"
export const LOAN_DISBURSAL_FAILURE="LOAN_DISBURSAL_FAILURE"



export const LOAN_FILTER_REQUEST="LOAN_FILTER_REQUEST"

export const LOAN_FILTER_SUCCESS="LOAN_FILTER_SUCCESS"

export const LOAN_FILTER_FAILURE="LOAN_FILTER_FAILURE"



export const ACTIVE_LOAN_DETAIL_REQUEST="ACTIVE_LOAN_DETAIL_REQUEST"

export const ACTIVE_LOAN_DETAIL_SUCCESS="ACTIVE_LOAN_DETAIL_SUCCESS"

export const ACTIVE_LOAN_DETAIL_FAILURE="ACTIVE_LOAN_DETAIL_FAILURE"




export const UTR_BULK_UPLOAD_REQUEST="UTR_BULK_UPLOAD_REQUEST"

export const UTR_BULK_UPLOAD_SUCCESS="UTR_BULK_UPLOAD_SUCCESS"

export const UTR_BULK_UPLOAD_FAILURE="UTR_BULK_UPLOAD_FAILURE"