export const CREATE_STATE_REQUEST = "CREATE_STATE_REQUEST";
export const CREATE_STATE_SUCCESS = "CREATE_STATE_SUCCESS";
export const CREATE_STATE_FAILURE = "CREATE_STATE_FAILURE";


export const LOAD_STATE_REQUEST = "LOAD_STATE_REQUEST";
export const LOAD_STATE_SUCCESS = "LOAD_STATE_SUCCESS";
export const LOAD_STATE_FAILURE = "LOAD_STATE_FAILURE";

export const GET_STATE_DETAILS_REQUEST = "GET_STATE_DETAILS_REQUEST";
export const GET_STATE_DETAILS_SUCCESS = "GET_STATE_DETAILS_SUCCESS";
export const GET_STATE_DETAILS_FAILURE = "GET_STATE_DETAILS_FAILURE";



export const UPDATE_STATE_REQUEST = "UPDATE_STATE_REQUEST";
export const UPDATE_STATE_SUCCESS = "UPDATE_STATE_SUCCESS";
export const UPDATE_STATE_FAILURE = "UPDATE_STATE_FAILURE";

export const DELETE_STATE_REQUEST = "DELETE_STATE_REQUEST";
export const DELETE_STATE_SUCCESS = "DELETE_STATE_SUCCESS";
export const DELETE_STATE_FAILURE = "DELETE_STATE_FAILURE";

